### ISSUE TITLE
`asset` doesn't work with JavaScript code splitting enabled

### ISSUE THREAD

**Issue by keichinger** [Becklyn/AssetsBundle#12]
Whenever code splitting for JavaScript is enabled, trying to call `asset("@namespace/code-splitted.js")` doesn't work deterministically since it may or may not return multiple URLs, depending on whether the JavaScript has been split into multiple, smaller chunks.

The current behavior is that an exception will be thrown since the `_dependencies.json` map isn't loaded and thus returns an "asset '<path>/namespace/code-splitted.js' can't be found".

**Comment by apfelbox** [comment]
Fixed with `asset_link` and the parsing of `_dependencies.json` in v4.
